# Generated by Django 4.2.10 on 2024-02-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_product_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cover",
            field=models.ImageField(default="/img/test.png", upload_to="img/"),
        ),
    ]
