# Generated by Django 4.2.10 on 2024-02-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_product_cover"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="cover",
        ),
        migrations.AddField(
            model_name="product",
            name="banner",
            field=models.FileField(default="", upload_to="banners"),
        ),
    ]
