# Generated by Django 4.2.10 on 2024-02-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_remove_product_cover_product_banner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="banner",
        ),
        migrations.AddField(
            model_name="product",
            name="cover",
            field=models.FileField(default="img/test.png", upload_to="myproduct"),
        ),
    ]
