# Generated by Django 4.2.10 on 2024-02-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_remove_product_banner_product_cover"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="cover",
        ),
        migrations.AddField(
            model_name="product",
            name="picture",
            field=models.ImageField(default="img/test.png", upload_to="myproduct"),
        ),
    ]
