# Generated by Django 4.2.10 on 2024-03-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_remove_product_cover_product_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "discount",
                    models.PositiveIntegerField(help_text="discount in percentage"),
                ),
                ("active", models.BooleanField(default=True)),
                ("active_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
    ]
