# Generated by Django 4.2.10 on 2024-03-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_flashsales_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashsales",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashsales",
                to="product.category",
            ),
        ),
    ]
