# Generated by Django 4.2.10 on 2024-02-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_order_admin_share_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="admin_share_amount",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="admin_share_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
