# Generated by Django 5.0.1 on 2024-02-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_admin_share_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('On the way', 'On the way'), ('Delivered', 'Delivered')], default='Received', max_length=15),
        ),
    ]
