# Generated by Django 4.2.10 on 2024-02-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_remove_order_admin_share_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Recieved", "Recieved"),
                    ("On the way", "On the way"),
                    ("Delivered", "Delivered"),
                ],
                max_length=15,
            ),
        ),
    ]
