# Generated by Django 4.2.10 on 2024-02-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_orderitem_options_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Recieved", "Recieved"),
                    ("On the way", "On the way"),
                    ("Delivered", "Delivered"),
                ],
                default="Recieved",
                max_length=15,
            ),
        ),
    ]
